[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

# 1) l'app sous /app (fallback SPA de l'app)
[[redirects]]
  from = "/app/*"
  to = "/app/index.html"
  status = 200

# 2) le site (fallback SPA du site)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200