[build]
  publish = "."
  functions = "netlify/functions"

[functions]  
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

# SPA app
[[redirects]]
  from = "/app/*"
  to = "/app/index.html"
  status = 200

# SPA site
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200