[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Edge Functions (QR)
[[edge_functions]]
  path = "/.netlify/functions/qr_put"
  function = "qr_put"

[[edge_functions]]
  path = "/.netlify/functions/qr_get"
  function = "qr_get"

# SPA app fallback
[[redirects]]
  from = "/app/*"
  to = "/app/index.html"
  status = 200

# SPA site fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200